// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBik9H1oZPI42gYmoM0fX9Q9kzOzBqHfRY',
    appId: '1:689030757641:web:fe66dc39be5fb4fea4e7d8',
    messagingSenderId: '689030757641',
    projectId: 'rabbit-kingdom-2759a',
    authDomain: 'rabbit-kingdom-2759a.firebaseapp.com',
    storageBucket: 'rabbit-kingdom-2759a.firebasestorage.app',
    measurementId: 'G-6SY73Q2WEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFBsvg-DVmGUq8mBa6tZsEMFLGXxfXRU',
    appId: '1:689030757641:android:b51e70d8a55d252ea4e7d8',
    messagingSenderId: '689030757641',
    projectId: 'rabbit-kingdom-2759a',
    storageBucket: 'rabbit-kingdom-2759a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemZ03nKarNEhlbYloSE6OsEUepaDzjeQ',
    appId: '1:689030757641:ios:d2c05b52aea22dafa4e7d8',
    messagingSenderId: '689030757641',
    projectId: 'rabbit-kingdom-2759a',
    storageBucket: 'rabbit-kingdom-2759a.firebasestorage.app',
    androidClientId: '689030757641-7s50b8fabhjsh1d9t2ivqedsn070kks0.apps.googleusercontent.com',
    iosClientId: '689030757641-d6lrag0c858j89nppoknbijmi50hv8do.apps.googleusercontent.com',
    iosBundleId: 'io.github.emurabbit.rabbitKingdom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemZ03nKarNEhlbYloSE6OsEUepaDzjeQ',
    appId: '1:689030757641:ios:e2ba9737b8d26ca7a4e7d8',
    messagingSenderId: '689030757641',
    projectId: 'rabbit-kingdom-2759a',
    storageBucket: 'rabbit-kingdom-2759a.firebasestorage.app',
    androidClientId: '689030757641-7s50b8fabhjsh1d9t2ivqedsn070kks0.apps.googleusercontent.com',
    iosClientId: '689030757641-glbl9iij6tb25jqd5i2pvi9tukrna6gr.apps.googleusercontent.com',
    iosBundleId: 'io.github.emurabbit.rabbitKingdom.RunnerTests',
  );
}
